export const models = [
  { value: "svc", label: "Support vector machine" },
  { value: "decision", label: "Decision Tree" },
  { value: "random", label: "Random Forest" },
  { value: "knn", label: "K-Nearest Neighbors" },
  { value: "qda", label: "Quadratic Discriminant Analysis" },
  { value: "mlp", label: "Multilayer Perceptron" },
  { value: "gnb", label: "Naive Bayes" },
];

export const roles = [
  { label: "Digital Marketing Specialist", value: "Digital Marketing Specialist"},
  { label: "Web Developer", value: "Web Developer" },
  { label: "Operations Manager", value: "Operations Manager" },
  { label: "Network Engineer", value: "Network Engineer" },
  { label: "Event Manager", value: "Event Manager" },
  { label: "Software Tester", value: "Software Tester" },
  { label: "Teacher", value: "Teacher" },
  { label: "UX/UI Designer", value: "UX/UI Designer" },
  { label: "Wedding Planner", value: "Wedding Planner" },
  { label: "QA Analyst", value: "QA Analyst" },
  { label: "Litigation Attorney", value: "Litigation Attorney" },
  { label: "Mechanical Engineer", value: "Mechanical Engineer" },
  { label: "Network Administrator", value: "Network Administrator" },
  { label: "Account Manager", value: "Account Manager" },
  { label: "Brand Manager", value: "Brand Manager" },
  { label: "Social Worker", value: "Social Worker" },
  { label: "Social Media Coordinator", value: "Social Media Coordinator" },
  { label: "Email Marketing Specialist", value: "Email Marketing Specialist" },
  { label: "HR Generalist", value: "HR Generalist" },
  { label: "Legal Assistant", value: "Legal Assistant" },
  { label: "Nurse Practitioner", value: "Nurse Practitioner" },
  { label: "Account Director", value: "Account Director" },
  { label: "Software Engineer", value: "Software Engineer" },
  { label: "Purchasing Agent", value: "Purchasing Agent" },
  { label: "Sales Consultant", value: "Sales Consultant" },
  { label: "Civil Engineer", value: "Civil Engineer" },
  {
    label: "Network Security Specialist",
    value: "Network Security Specialist",
  },
  { label: "UI Developer", value: "UI Developer" },
  { label: "Financial Planner", value: "Financial Planner" },
  { label: "Event Planner", value: "Event Planner" },
  { label: "Psychologist", value: "Psychologist" },
  { label: "Electrical Designer", value: "Electrical Designer" },
  { label: "Data Analyst", value: "Data Analyst" },
  { label: "Technical Writer", value: "Technical Writer" },
  { label: "Tax Consultant", value: "Tax Consultant" },
  { label: "Account Executive", value: "Account Executive" },
  { label: "Systems Administrator", value: "Systems Administrator" },
  { label: "Database Administrator", value: "Database Administrator" },
  { label: "Research Analyst", value: "Research Analyst" },
  { label: "Data Entry Clerk", value: "Data Entry Clerk" },
  { label: "Registered Nurse", value: "Registered Nurse" },
  { label: "Investment Analyst", value: "Investment Analyst" },
  { label: "Speech Therapist", value: "Speech Therapist" },
  { label: "Sales Manager", value: "Sales Manager" },
  { label: "Landscape Architect", value: "Landscape Architect" },
  { label: "Key Account Manager", value: "Key Account Manager" },
  { label: "UX Researcher", value: "UX Researcher" },
  { label: "Investment Banker", value: "Investment Banker" },
  { label: "IT Support Specialist", value: "IT Support Specialist" },
  { label: "Art Director", value: "Art Director" },
  { label: "Software Developer", value: "Software Developer" },
  { label: "Project Manager", value: "Project Manager" },
  { label: "Customer Service Manager", value: "Customer Service Manager" },
  { label: "Procurement Manager", value: "Procurement Manager" },
  { label: "Substance Abuse Counselor", value: "Substance Abuse Counselor" },
  { label: "Supply Chain Analyst", value: "Supply Chain Analyst" },
  { label: "Data Engineer", value: "Data Engineer" },
  { label: "Accountant", value: "Accountant" },
  { label: "Sales Representative", value: "Sales Representative" },
  { label: "Environmental Consultant", value: "Environmental Consultant" },
  { label: "Electrical Engineer", value: "Electrical Engineer" },
  { label: "Systems Engineer", value: "Systems Engineer" },
  { label: "Art Teacher", value: "Art Teacher" },
  { label: "Human Resources Manager", value: "Human Resources Manager" },
  { label: "Inventory Analyst", value: "Inventory Analyst" },
  { label: "Legal Counsel", value: "Legal Counsel" },
  { label: "Database Developer", value: "Database Developer" },
  { label: "Procurement Specialist", value: "Procurement Specialist" },
  { label: "Systems Analyst", value: "Systems Analyst" },
  { label: "Copywriter", value: "Copywriter" },
  { label: "Content Writer", value: "Content Writer" },
  { label: "HR Coordinator", value: "HR Coordinator" },
  { label: "Business Development Manager", value: "Business Development Manager"},
  { label: "Java Developer", value: "Java Developer" },
  { label: "Supply Chain Manager", value: "Supply Chain Manager" },
  { label: "Event Coordinator", value: "Event Coordinator" },
  { label: "Family Nurse Practitioner", value: "Family Nurse Practitioner" },
  { label: "Front-End Engineer", value: "Front-End Engineer" },
  { label: "Customer Success Manager", value: "Customer Success Manager" },
  { label: "Procurement Coordinator", value: "Procurement Coordinator" },
  { label: "Urban Planner", value: "Urban Planner" },
  { label: "Architectural Designer", value: "Architectural Designer" },
  { label: "Financial Analyst", value: "Financial Analyst" },
  { label: "Environmental Engineer", value: "Environmental Engineer" },
  { label: "Back-End Developer", value: "Back-End Developer" },
  { label: "Structural Engineer", value: "Structural Engineer" },
  { label: "Market Research Analyst", value: "Market Research Analyst" },
  { label: "Customer Service Representative", value: "Customer Service Representative"},
  { label: "Customer Support Specialist", value: "Customer Support Specialist"},
  { label: "Business Analyst", value: "Business Analyst" },
  { label: "Social Media Manager", value: "Social Media Manager" },
  { label: "Family Lawyer", value: "Family Lawyer" },
  { label: "Chemical Analyst", value: "Chemical Analyst" },
  { label: "Network Technician", value: "Network Technician" },
  { label: "Interior Designer", value: "Interior Designer" },
  { label: "Software Architect", value: "Software Architect" },
  { label: "Nurse Manager", value: "Nurse Manager" },
  { label: "Veterinarian", value: "Veterinarian" },
  { label: "Process Engineer", value: "Process Engineer" },
  { label: "IT Manager", value: "IT Manager" },
  { label: "Quality Assurance Analyst", value: "Quality Assurance Analyst" },
  { label: "Pharmaceutical Sales Representative", value: "Pharmaceutical Sales Representative"},
  { label: "Office Manager", value: "Office Manager" },
  { label: "Architect", value: "Architect" },
  { label: "Physician Assistant", value: "Physician Assistant" },
  { label: "Marketing Director", value: "Marketing Director" },
  { label: "Front-End Developer", value: "Front-End Developer" },
  { label: "Research Scientist", value: "Research Scientist" },
  { label: "Executive Assistant", value: "Executive Assistant" },
  { label: "HR Manager", value: "HR Manager" },
  { label: "Marketing Manager", value: "Marketing Manager" },
  { label: "Public Relations Specialist", value: "Public Relations Specialist"},
  { label: "Financial Controller", value: "Financial Controller" },
  { label: "Investment Advisor", value: "Investment Advisor" },
  { label: "Aerospace Engineer", value: "Aerospace Engineer" },
  { label: "Marketing Analyst", value: "Marketing Analyst" },
  { label: "Paralegal", value: "Paralegal" },
  { label: "Landscape Designer", value: "Landscape Designer" },
  { label: "Web Designer", value: "Web Designer" },
  { label: "Occupational Therapist", value: "Occupational Therapist" },
  { label: "Legal Advisor", value: "Legal Advisor" },
  { label: "Marketing Coordinator", value: "Marketing Coordinator" },
  { label: "Dental Hygienist", value: "Dental Hygienist" },
  { label: "SEM Specialist", value: "SEM Specialist" },
  { label: "SEO Specialist", value: "SEO Specialist" },
  { label: "Pediatrician", value: "Pediatrician" },
  { label: "QA Engineer", value: "QA Engineer" },
  { label: "Data Scientist", value: "Data Scientist" },
  { label: "Financial Advisor", value: "Financial Advisor" },
  { label: "Personal Assistant", value: "Personal Assistant" },
  { label: "SEO Analyst", value: "SEO Analyst" },
  { label: "Network Analyst", value: "Network Analyst" },
  { label: "Mechanical Designer", value: "Mechanical Designer" },
  { label: "Marketing Specialist", value: "Marketing Specialist" },
  { label: "Graphic Designer", value: "Graphic Designer" },
  { label: "Finance Manager", value: "Finance Manager" },
  { label: "Physical Therapist", value: "Physical Therapist" },
  { label: "Product Designer", value: "Product Designer" },
  { label: "Administrative Assistant", value: "Administrative Assistant" },
  { label: "Brand Ambassador", value: "Brand Ambassador" },
  { label: "Project Coordinator", value: "Project Coordinator" },
  { label: "Product Manager", value: "Product Manager" },
  { label: "IT Administrator", value: "IT Administrator" },
  { label: "Sales Associate", value: "Sales Associate" },
  { label: "Chemical Engineer", value: "Chemical Engineer" },
  { label: "Legal Secretary", value: "Legal Secretary" },
  { label: "Market Analyst", value: "Market Analyst" },
];

export const jobs = [
    { label: 'Digital Marketing Specialist', value: 'Digital Marketing Specialist' },
    { label: 'Web Developer', value: 'Web Developer' },
    { label: 'Operations Manager', value: 'Operations Manager' },
    { label: 'Network Engineer', value: 'Network Engineer' },
    { label: 'Event Manager', value: 'Event Manager' },
    { label: 'Software Tester', value: 'Software Tester' },
    { label: 'Teacher', value: 'Teacher' },
    { label: 'UX/UI Designer', value: 'UX/UI Designer' },
    { label: 'Wedding Planner', value: 'Wedding Planner' },
    { label: 'QA Analyst', value: 'QA Analyst' },
    { label: 'Litigation Attorney', value: 'Litigation Attorney' },
    { label: 'Mechanical Engineer', value: 'Mechanical Engineer' },
    { label: 'Network Administrator', value: 'Network Administrator' },
    { label: 'Account Manager', value: 'Account Manager' },
    { label: 'Brand Manager', value: 'Brand Manager' },
    { label: 'Social Worker', value: 'Social Worker' },
    { label: 'Social Media Coordinator', value: 'Social Media Coordinator' },
    { label: 'Email Marketing Specialist', value: 'Email Marketing Specialist' },
    { label: 'HR Generalist', value: 'HR Generalist' },
    { label: 'Legal Assistant', value: 'Legal Assistant' },
    { label: 'Nurse Practitioner', value: 'Nurse Practitioner' },
    { label: 'Account Director', value: 'Account Director' },
    { label: 'Software Engineer', value: 'Software Engineer' },
    { label: 'Purchasing Agent', value: 'Purchasing Agent' },
    { label: 'Sales Consultant', value: 'Sales Consultant' },
    { label: 'Civil Engineer', value: 'Civil Engineer' },
    { label: 'Network Security Specialist', value: 'Network Security Specialist' },
    { label: 'UI Developer', value: 'UI Developer' },
    { label: 'Financial Planner', value: 'Financial Planner' },
    { label: 'Event Planner', value: 'Event Planner' },
    { label: 'Psychologist', value: 'Psychologist' },
    { label: 'Electrical Designer', value: 'Electrical Designer' },
    { label: 'Data Analyst', value: 'Data Analyst' },
    { label: 'Technical Writer', value: 'Technical Writer' },
    { label: 'Tax Consultant', value: 'Tax Consultant' },
    { label: 'Account Executive', value: 'Account Executive' },
    { label: 'Systems Administrator', value: 'Systems Administrator' },
    { label: 'Database Administrator', value: 'Database Administrator' },
    { label: 'Research Analyst', value: 'Research Analyst' },
    { label: 'Data Entry Clerk', value: 'Data Entry Clerk' },
    { label: 'Registered Nurse', value: 'Registered Nurse' },
    { label: 'Investment Analyst', value: 'Investment Analyst' },
    { label: 'Speech Therapist', value: 'Speech Therapist' },
    { label: 'Sales Manager', value: 'Sales Manager' },
    { label: 'Landscape Architect', value: 'Landscape Architect' },
    { label: 'Key Account Manager', value: 'Key Account Manager' },
    { label: 'UX Researcher', value: 'UX Researcher' },
    { label: 'Investment Banker', value: 'Investment Banker' },
    { label: 'IT Support Specialist', value: 'IT Support Specialist' },
    { label: 'Art Director', value: 'Art Director' },
    { label: 'Software Developer', value: 'Software Developer' },
    { label: 'Project Manager', value: 'Project Manager' },
    { label: 'Customer Service Manager', value: 'Customer Service Manager' },
    { label: 'Procurement Manager', value: 'Procurement Manager' },
    { label: 'Substance Abuse Counselor', value: 'Substance Abuse Counselor' },
    { label: 'Supply Chain Analyst', value: 'Supply Chain Analyst' },
    { label: 'Data Engineer', value: 'Data Engineer' },
    { label: 'Accountant', value: 'Accountant' },
    { label: 'Sales Representative', value: 'Sales Representative' },
    { label: 'Environmental Consultant', value: 'Environmental Consultant' },
    { label: 'Electrical Engineer', value: 'Electrical Engineer' },
    { label: 'Systems Engineer', value: 'Systems Engineer' },
    { label: 'Art Teacher', value: 'Art Teacher' },
    { label: 'Human Resources Manager', value: 'Human Resources Manager' },
    { label: 'Inventory Analyst', value: 'Inventory Analyst' },
    { label: 'Legal Counsel', value: 'Legal Counsel' },
    { label: 'Database Developer', value: 'Database Developer' },
    { label: 'Procurement Specialist', value: 'Procurement Specialist' },
    { label: 'Systems Analyst', value: 'Systems Analyst' },
    { label: 'Copywriter', value: 'Copywriter' },
    { label: 'Content Writer', value: 'Content Writer' },
    { label: 'HR Coordinator', value: 'HR Coordinator' },
    { label: 'Business Development Manager', value: 'Business Development Manager' },
    { label: 'Java Developer', value: 'Java Developer' },
    { label: 'Supply Chain Manager', value: 'Supply Chain Manager' },
    { label: 'Event Coordinator', value: 'Event Coordinator' },
    { label: 'Family Nurse Practitioner', value: 'Family Nurse Practitioner' },
    { label: 'Front-End Engineer', value: 'Front-End Engineer' },
    { label: 'Customer Success Manager', value: 'Customer Success Manager' },
    { label: 'Procurement Coordinator', value: 'Procurement Coordinator' },
    { label: 'Urban Planner', value: 'Urban Planner' },
    { label: 'Architectural Designer', value: 'Architectural Designer' },
    { label: 'Financial Analyst', value: 'Financial Analyst' },
    { label: 'Environmental Engineer', value: 'Environmental Engineer' },
    { label: 'Back-End Developer', value: 'Back-End Developer' },
    { label: 'Structural Engineer', value: 'Structural Engineer' },
    { label: 'Market Research Analyst', value: 'Market Research Analyst' },
    { label: 'Customer Service Representative', value: 'Customer Service Representative' },
    { label: 'Customer Support Specialist', value: 'Customer Support Specialist' },
    { label: 'Business Analyst', value: 'Business Analyst' },
    { label: 'Social Media Manager', value: 'Social Media Manager' },
    { label: 'Family Lawyer', value: 'Family Lawyer' },
    { label: 'Chemical Analyst', value: 'Chemical Analyst' },
    { label: 'Network Technician', value: 'Network Technician' },
    { label: 'Interior Designer', value: 'Interior Designer' },
    { label: 'Software Architect', value: 'Software Architect' },
    { label: 'Nurse Manager', value: 'Nurse Manager' },
    { label: 'Veterinarian', value: 'Veterinarian' },
    { label: 'Process Engineer', value: 'Process Engineer' },
    { label: 'IT Manager', value: 'IT Manager' },
    { label: 'Quality Assurance Analyst', value: 'Quality Assurance Analyst' },
    { label: 'Pharmaceutical Sales Representative', value: 'Pharmaceutical Sales Representative' },
    { label: 'Office Manager', value: 'Office Manager' },
    { label: 'Architect', value: 'Architect' },
    { label: 'Physician Assistant', value: 'Physician Assistant' },
    { label: 'Marketing Director', value: 'Marketing Director' },
    { label: 'Front-End Developer', value: 'Front-End Developer' },
    { label: 'Research Scientist', value: 'Research Scientist' },
    { label: 'Executive Assistant', value: 'Executive Assistant' },
    { label: 'HR Manager', value: 'HR Manager' },
    { label: 'Marketing Manager', value: 'Marketing Manager' },
    { label: 'Public Relations Specialist', value: 'Public Relations Specialist' },
    { label: 'Financial Controller', value: 'Financial Controller' },
    { label: 'Investment Advisor', value: 'Investment Advisor' },
    { label: 'Aerospace Engineer', value: 'Aerospace Engineer' },
    { label: 'Marketing Analyst', value: 'Marketing Analyst' },
    { label: 'Paralegal', value: 'Paralegal' },
    { label: 'Landscape Designer', value: 'Landscape Designer' },
    { label: 'Web Designer', value: 'Web Designer' },
    { label: 'Occupational Therapist', value: 'Occupational Therapist' },
    { label: 'Legal Advisor', value: 'Legal Advisor' },
    { label: 'Marketing Coordinator', value: 'Marketing Coordinator' },
    { label: 'Dental Hygienist', value: 'Dental Hygienist' },
    { label: 'SEM Specialist', value: 'SEM Specialist' },
    { label: 'SEO Specialist', value: 'SEO Specialist' },
    { label: 'Pediatrician', value: 'Pediatrician' },
    { label: 'QA Engineer', value: 'QA Engineer' },
    { label: 'Data Scientist', value: 'Data Scientist' },
    { label: 'Financial Advisor', value: 'Financial Advisor' },
    { label: 'Personal Assistant', value: 'Personal Assistant' },
    { label: 'SEO Analyst', value: 'SEO Analyst' },
    { label: 'Network Analyst', value: 'Network Analyst' },
    { label: 'Mechanical Designer', value: 'Mechanical Designer' },
    { label: 'Marketing Specialist', value: 'Marketing Specialist' },
    { label: 'Graphic Designer', value: 'Graphic Designer' },
    { label: 'Finance Manager', value: 'Finance Manager' },
    { label: 'Physical Therapist', value: 'Physical Therapist' },
    { label: 'Product Designer', value: 'Product Designer' },
    { label: 'Administrative Assistant', value: 'Administrative Assistant' },
    { label: 'Brand Ambassador', value: 'Brand Ambassador' },
    { label: 'Project Coordinator', value: 'Project Coordinator' },
    { label: 'Product Manager', value: 'Product Manager' },
    { label: 'IT Administrator', value: 'IT Administrator' },
    { label: 'Sales Associate', value: 'Sales Associate' },
    { label: 'Chemical Engineer', value: 'Chemical Engineer' },
    { label: 'Legal Secretary', value: 'Legal Secretary' },
    { label: 'Market Analyst', value: 'Market Analyst' }
  ]
  
export const genders = [
  {value: "Male", label: "Male"},
  {value: "Female", label: "Female"}
]

export const qualifications = [
  { value: "M.Tech", label: "M.Tech" },
  { value: "BCA", label: "BCA" },
  { value: "PhD", label: "PhD" },
  { value: "MBA", label: "MBA" },
  { value: "MCA", label: "MCA" },
  { value: "M.Com", label: "M.Com" },
  { value: "BBA", label: "BBA" },
  { value: "B.Tech", label: "B.Tech" },
  { value: "B.Com", label: "B.Com" },
  { value: "BA", label: "BA" },
];

export const work_type = [
  { label: "Intern", value: "Intern" },
  { label: "Temporary", value: "Temporary" },
  { label: "Full-Time", value: "Full-Time" },
  { label: "Contract", value: "Contract" },
  { label: "Part-Time", value: "Part-Time" },
];


export const countries = [
  { label: 'Isle of Man', value: 'Isle of Man' },
  { label: 'Turkmenistan', value: 'Turkmenistan' },
  { label: 'Macao SAR, China', value: 'Macao SAR, China' },
  { label: 'Benin', value: 'Benin' },
  { label: 'Chile', value: 'Chile' },
  { label: 'Belgium', value: 'Belgium' },
  { label: 'Cayman Islands', value: 'Cayman Islands' },
  { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe' },
  { label: 'Maldives', value: 'Maldives' },
  { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
  { label: 'Bahrain', value: 'Bahrain' },
  { label: 'Bermuda', value: 'Bermuda' },
  { label: 'Jamaica', value: 'Jamaica' },
  { label: 'Gambia', value: 'Gambia' },
  { label: 'Syrian Arab Republic', value: 'Syrian Arab Republic' },
  { label: 'Yemen', value: 'Yemen' },
  { label: 'San Marino', value: 'San Marino' },
  { label: 'French Polynesia', value: 'French Polynesia' },
  { label: 'North Korea', value: 'North Korea' },
  { label: 'Democratic Republic Of Congo', value: 'Democratic Republic Of Congo' },
  { label: 'Azerbaijan', value: 'Azerbaijan' },
  { label: 'Tuvalu', value: 'Tuvalu' },
  { label: 'Eritrea', value: 'Eritrea' },
  { label: 'Honduras', value: 'Honduras' },
  { label: 'British Virgin Islands', value: 'British Virgin Islands' },
  { label: 'Cuba', value: 'Cuba' },
  { label: 'Hungary', value: 'Hungary' },
  { label: 'Paraguay', value: 'Paraguay' },
  { label: 'Jordan', value: 'Jordan' },
  { label: 'Nigeria', value: 'Nigeria' },
  { label: 'Libya', value: 'Libya' },
  { label: 'Australia', value: 'Australia' },
  { label: 'New Caledonia', value: 'New Caledonia' },
  { label: 'Oman', value: 'Oman' },
  { label: 'West Bank and Gaza', value: 'West Bank and Gaza' },
  { label: 'Solomon Islands', value: 'Solomon Islands' },
  { label: 'Cote d\'Ivoire', value: 'Cote d\'Ivoire' },
  { label: 'Ecuador', value: 'Ecuador' },
  { label: 'Virgin Islands (U.S.)', value: 'Virgin Islands (U.S.)' },
  { label: 'Cameroon', value: 'Cameroon' },
  { label: 'Comoros', value: 'Comoros' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Belize', value: 'Belize' },
  { label: 'Malta', value: 'Malta' },
  { label: 'Panama', value: 'Panama' },
  { label: 'Republic Of Congo', value: 'Republic Of Congo' },
  { label: 'Turks and Caicos Islands', value: 'Turks and Caicos Islands' },
  { label: 'Cambodia', value: 'Cambodia' },
  { label: 'Monaco', value: 'Monaco' },
  { label: 'Armenia', value: 'Armenia' },
  { label: 'Guam', value: 'Guam' },
  { label: 'St. Lucia', value: 'St. Lucia' },
  { label: 'India', value: 'India' },
  { label: 'Somalia', value: 'Somalia' },
  { label: 'Pakistan', value: 'Pakistan' },
  { label: 'Brunei', value: 'Brunei' },
  { label: 'Dominica', value: 'Dominica' },
  { label: 'UK', value: 'UK' },
  { label: 'Afghanistan', value: 'Afghanistan' },
  { label: 'Mongolia', value: 'Mongolia' },
  { label: 'Slovak Republic', value: 'Slovak Republic' },
  { label: 'Morocco', value: 'Morocco' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'Botswana', value: 'Botswana' },
  { label: 'St. Martin (French part)', value: 'St. Martin (French part)' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia' },
  { label: 'Bangladesh', value: 'Bangladesh' },
  { label: 'Nepal', value: 'Nepal' },
  { label: 'Malaysia', value: 'Malaysia' },
  { label: 'Kyrgyz Republic', value: 'Kyrgyz Republic' },
  { label: 'Sri Lanka', value: 'Sri Lanka' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Moldova', value: 'Moldova' },
  { label: 'Guatemala', value: 'Guatemala' },
  { label: 'Russia', value: 'Russia' },
  { label: 'Latvia', value: 'Latvia' },
  { label: 'Germany', value: 'Germany' },
  { label: 'Djibouti', value: 'Djibouti' },
  { label: 'Suriname', value: 'Suriname' },
  { label: 'Mauritius', value: 'Mauritius' },
  { label: 'Mali', value: 'Mali' },
  { label: 'Costa Rica', value: 'Costa Rica' },
  { label: 'Indonesia', value: 'Indonesia' },
  { label: 'Fiji', value: 'Fiji' },
  { label: 'Rwanda', value: 'Rwanda' },
  { label: 'South Sudan', value: 'South Sudan' },
  { label: 'Lao PDR', value: 'Lao PDR' },
  { label: 'Puerto Rico', value: 'Puerto Rico' },
  { label: 'Japan', value: 'Japan' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Philippines', value: 'Philippines' },
  { label: 'Luxembourg', value: 'Luxembourg' },
  { label: 'Cabo Verde', value: 'Cabo Verde' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea' },
  { label: 'Senegal', value: 'Senegal' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Lesotho', value: 'Lesotho' },
  { label: 'Denmark', value: 'Denmark' },
  { label: 'Kuwait', value: 'Kuwait' },
  { label: 'Vanuatu', value: 'Vanuatu' },
  { label: 'Zambia', value: 'Zambia' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
  { label: 'Uganda', value: 'Uganda' },
  { label: 'Hong Kong SAR, China', value: 'Hong Kong SAR, China' },
  { label: 'Czech Republic', value: 'Czech Republic' },
  { label: 'Central African Republic', value: 'Central African Republic' },
  { label: 'USA', value: 'USA' },
  { label: 'Uruguay', value: 'Uruguay' },
  { label: 'Madagascar', value: 'Madagascar' },
  { label: 'Macedonia, FYR', value: 'Macedonia, FYR' },
  { label: 'Haiti', value: 'Haiti' },
  { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { label: 'Liberia', value: 'Liberia' },
  { label: 'Barbados', value: 'Barbados' },
  { label: 'Iran, Islamic Rep.', value: 'Iran, Islamic Rep.' },
  { label: 'Dominican Republic', value: 'Dominican Republic' },
  { label: 'Singapore', value: 'Singapore' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Guinea', value: 'Guinea' },
  { label: 'Palau', value: 'Palau' },
  { label: 'Gibraltar', value: 'Gibraltar' },
  { label: 'Seychelles', value: 'Seychelles' },
  { label: 'Iraq', value: 'Iraq' },
  { label: 'Kenya', value: 'Kenya' },
  { label: 'Romania', value: 'Romania' },
  { label: 'Cyprus', value: 'Cyprus' },
  { label: 'Mauritania', value: 'Mauritania' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'France', value: 'France' },
  { label: 'Timor-Leste', value: 'Timor-Leste' },
  { label: 'American Samoa', value: 'American Samoa' },
  { label: 'Chad', value: 'Chad' },
  { label: 'Ireland', value: 'Ireland' },
  { label: 'Ghana', value: 'Ghana' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Thailand', value: 'Thailand' },
  { label: 'Uzbekistan', value: 'Uzbekistan' },
  { label: 'Myanmar', value: 'Myanmar' },
  { label: 'St. Vincent and the Grenadines', value: 'St. Vincent and the Grenadines' },
  { label: 'Burkina Faso', value: 'Burkina Faso' },
  { label: 'Faroe Islands', value: 'Faroe Islands' },
  { label: 'Greenland', value: 'Greenland' },
  { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
  { label: 'Kazakhstan', value: 'Kazakhstan' },
  { label: 'Nicaragua', value: 'Nicaragua' },
  { label: 'China', value: 'China' },
  { label: 'Liechtenstein', value: 'Liechtenstein' },
  { label: 'Poland', value: 'Poland' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'Korea, Rep.', value: 'Korea, Rep.' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Eswatini', value: 'Eswatini' },
  { label: 'Tanzania', value: 'Tanzania' },
  { label: 'Venezuela, RB', value: 'Venezuela, RB' },
  { label: 'Israel', value: 'Israel' },
  { label: 'Bhutan', value: 'Bhutan' },
  { label: 'Zimbabwe', value: 'Zimbabwe' },
  { label: 'Andorra', value: 'Andorra' },
  { label: 'Egypt', value: 'Egypt' },
  { label: 'St. Kitts and Nevis', value: 'St. Kitts and Nevis' },
  { label: 'Samoa', value: 'Samoa' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Sudan', value: 'Sudan' },
  { label: 'Canada', value: 'Canada' },
  { label: 'New Zealand', value: 'New Zealand' },
  { label: 'Sierra Leone', value: 'Sierra Leone' },
  { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
  { label: 'UAE', value: 'UAE' },
  { label: 'Togo', value: 'Togo' },
  { label: 'Gabon', value: 'Gabon' },
  { label: 'Bulgaria', value: 'Bulgaria' },
  { label: 'Iceland', value: 'Iceland' },
  { label: 'Curacao', value: 'Curacao' },
  { label: 'Qatar', value: 'Qatar' },
  { label: 'Tunisia', value: 'Tunisia' },
  { label: 'Ethiopia', value: 'Ethiopia' },
  { label: 'Micronesia, Fed. Sts.', value: 'Micronesia, Fed. Sts.' },
  { label: 'Guyana', value: 'Guyana' },
  { label: 'Sint Maarten (Dutch part)', value: 'Sint Maarten (Dutch part)' },
  { label: 'Tonga', value: 'Tonga' },
  { label: 'El Salvador', value: 'El Salvador' },
  { label: 'Finland', value: 'Finland' },
  { label: 'Burundi', value: 'Burundi' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Niger', value: 'Niger' },
  { label: 'Greece', value: 'Greece' },
  { label: 'Angola', value: 'Angola' },
  { label: 'Aruba', value: 'Aruba' },
  { label: 'Estonia', value: 'Estonia' },
  { label: 'Grenada', value: 'Grenada' },
  { label: 'Kiribati', value: 'Kiribati' },
  { label: 'Lithuania', value: 'Lithuania' },
  { label: 'Belarus', value: 'Belarus' },
  { label: 'Lebanon', value: 'Lebanon' },
  { label: 'Croatia', value: 'Croatia' },
  { label: 'Mozambique', value: 'Mozambique' },
  { label: 'Georgia', value: 'Georgia' },
  { label: 'Tajikistan', value: 'Tajikistan' },
  { label: 'Serbia', value: 'Serbia' },
  { label: 'Kosovo', value: 'Kosovo' },
  { label: 'Namibia', value: 'Namibia' },
  { label: 'Nauru', value: 'Nauru' },
  { label: 'Malawi', value: 'Malawi' },
  { label: 'Montenegro', value: 'Montenegro' },
  { label: 'Algeria', value: 'Algeria' },
  { label: 'Bahamas, The', value: 'Bahamas, The' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Austria', value: 'Austria' },
  { label: 'Ukraine', value: 'Ukraine' },
  { label: 'Albania', value: 'Albania' },
  { label: 'Marshall Islands', value: 'Marshall Islands' },
  { label: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
  { label: 'Vietnam', value: 'Vietnam' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Slovenia', value: 'Slovenia' }
]